config/routes.rb
Rails.application.routes.draw do
resources :advertisements

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#only:[] is used so /posrs/:id routes aren't created. Only posts/:post_is/comments
resources :posts, only: [] do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
end

resources :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]


post 'users/confirm' => 'users#confirm'

get 'users' =>'users#create'

get 'about' => 'welcome#about'

  get 'welcome/contact'

  #added my route to faq page
  get 'welcome/faq'

#default page the app will load
  root 'welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    if @question.save
      flash[:notice] = "Question was asked!"
      redirect_to @question
    else
      flash.now[:alert] = "There was an error saving the question. Please try again."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash.now[:alert] = "There was an error saving the question. Please try again."
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to questions_path
    else
      flash.now[:alert] = "There was an error deleting the question."
      render :show
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1 >Edit Question</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @question do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter updated question" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows:8, class: 'form-control', placeholder: "Enter updated question body" %>
    </div>
    <div>
      <p><b>Resolved: </b><%= f.check_box :resolved, options = {}, checked_value = "1", unchecked_value = "0"%></p>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1 class="center">All Questions</h1>
<% @questions.each do |question| %>
  <div class="media">
    <div class="media-body">
      <h4 clas="media-heading">
        <%= link_to question.title, question%>
      </h4>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<div class="row">
  <div class="col-md-4">
    <p>Remember — sometimes there <em>are</em> stupid questions.</p>
  </div>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:'form-control', placeholder:'Enter question title' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class:'form-control', placeholder:'Enter question body' %>
      </div>
      <div class="form-group">
        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      <div>
      <div class="form-group">
        <%= f.submit "Save", class:'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<div class="row center">
  <p><%= @question.body %></p>
</div>
<div class="row center">
  <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-info' %>
<%# Here we override the method(:question) with :delete, so that the when the button is clicked the route called is delete %>
  <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question? All answers will also be deleted.'} %>
</div>
<div class="row center">
  <hr style="width:300px;"/>
  <p><b>Resolved: </b><%= @question.resolved %></p>
</div>