config/routes.rb
Rails.application.routes.draw do
resources :advertisements

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#only:[] is used so /posrs/:id routes aren't created. Only posts/:post_is/comments
resources :posts, only: [] do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
end

resources :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]


post 'users/confirm' => 'users#confirm'

get 'users' =>'users#create'

get 'about' => 'welcome#about'

  get 'welcome/contact'

  #added my route to faq page
  get 'welcome/faq'

#default page the app will load
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :sponsored_posts
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
  validates :public, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
     @topic = Topic.new(topic_params)

     if @topic.save
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash.now[:alert] = "Error creating topic. Please try again."
       render :new
     end
   end

   def edit
     @topic = Topic.find(params[:id])
   end

   def update
     @topic = Topic.find(params[:id])

     @topic.assign_attributes(topic_params)

     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
   end

   def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end

   private
   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end

   def authorize_user
     unless current_user.admin? || current_user.moderator?
       flash[:alert] = "You must be an admin to do that."
       redirect_to topics_path
     end
   end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
      current_user != nil && (current_user.admin? || current_user.moderator?)
  end
end

app/views/topics/_form.html.erb
<%= form_for [topic] do |f| %>
  <% if topic.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter topic name' %>
  <% end %>

  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Enter description body' %>
  <% end %>

  <div class="form-group" style="margin: 0px 20px">
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media list">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: {topic: @topic} %>
   </div>
 </div>

app/views/topics/index.html.erb
<h1>Topics</h1>
<% if current_user != nil && current_user.admin? %>
  <div class="row center" style="padding-top:10px;">
    <%= link_to "Create New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
<% end %>
<hr />

 <%= render @topics %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: {topic: @topic} %>
   </div>
 </div>

app/views/topics/show.html.erb
<div class="container">
<!--BEGIN TOPIC DESCRIPTION-->
    <div class="row">
      <h1><%= @topic.name %></h1>
      <p class="lead center"><%= @topic.description %></p>
      <div class="center">
           <% if user_is_authorized_for_topics? %>
            <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-info' %>
          <% end %>
          <% if current_user != nil && (current_user == @topic.id || current_user.admin?) %>
            <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'} %>
           <% end %>
          <% if user_is_authorized_for_topics? %>
            <%= link_to "+", new_topic_post_path(@topic), class: 'btn btn-success btn-sm' %>
          <% end %>
          <% if current_user.member? %>
            <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
          <% end %>
      </div>
    </div>
<!--END TOPIC DESCRIPTION-->
<hr />
<!--BEGIN POST LIST-->
    <h3>
      Posts
    </h3>
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= render @topic.posts %>
      </div>
    <% end %>

     <% if current_user != nil && (current_user == @topic.id || current_user.admin?) %>
      <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?'} %>
     <% end %>

     <% if user_is_authorized_for_topics? %>
       <%= link_to "+", new_topic_post_path(@topic), class: 'btn btn-success btn-sm' %>
     <% end %>


<!--END POST LIST-->


<hr />


<!--BEGIN SPONSORED POSTS -->
    <h3>
      Sponsored Posts
      <% if user_is_authorized_for_topics? %>
       <%= link_to "+", new_topic_sponsored_post_path(@topic), class: 'btn btn-success btn-sm' %>
      <% end %>
    </h3>
    <% @topic.sponsored_posts.each do |sponsored_post| %>
         <div class="media list">
           <div class="media-body">
             <h4 class="media-heading">
               <%= link_to sponsored_post.title, topic_sponsored_post_path(@topic, sponsored_post) %>
             </h4>
           </div>
         </div>
    <% end %>
<!-- END SPONSORED POSTS -->
</div>