config/routes.rb
Rails.application.routes.draw do
resources :advertisements

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#only:[] is used so /posrs/:id routes aren't created. Only posts/:post_is/comments
resources :posts, only: [] do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
end

resources :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]


post 'users/confirm' => 'users#confirm'

get 'users' =>'users#create'

get 'about' => 'welcome#about'

  get 'welcome/contact'

  #added my route to faq page
  get 'welcome/faq'

#default page the app will load
  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_vote
  after_create :create_favorite

  default_scope {order('rank DESC')}
  scope :visible_to, -> (user) { user ? all : joins(topic).where('topics.public' => true) }
  scope :ordered_by_title, -> {order('title ASC')}
  scope :ordered_by_reverse_created_at, -> {order('title ASC')}
  #also tried:
  #scope :ordered_by_reverse_created_at, -> {order('created_at ASC')}


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
     votes.where(value: 1).count
   end

   def down_votes
     votes.where(value: -1).count
   end

   def points
     votes.sum(:value)
   end

   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

   private

   def create_vote
     user.votes.create(value: 1, post:self)
   end

   def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self).deliver_now
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in, except: :show
  before_action :authorize_user, except: [:show, :new, :create]

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
#we're associating the post with the user who created it
    @post.user = current_user
    if @post.save
      flash[:notice] = "Post was saved!"
#here we change the redirect to the topic Show view
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
#Set the redirect to the Topic Show view
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
#When a post is deleted, it redirects to the Topic Show view
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

#anything below this will be considered a private method and wont be able to be accessed except through Posts
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
     post = Post.find(params[:id])

     unless current_user == post.user || current_user.admin? || current_user.moderator?
       flash[:alert] = "You must be an admin to do that."
       redirect_to [post.topic, post]
     end
   end

   def after_create
    new_vote = Post.find(params[:id, :user])
   end

end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user !=nil && ((current_user == post.user || current_user.admin?) || (current_user == post.user || current_user.moderator?))
  end

  def no_posts(user)
    if user.posts.count == 0
      "#{user.name} has not submitted any posts yet."
    end
  end

end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>

  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voting', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="center">Edit post</h1>
<div class="row">
  <div class="col-md-4">
    <h4>Guidelines for posts</h4>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you banned.</li>
      <li>Keep it clean dam—... we mean, dang-it</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post </h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post} %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <!-- START POST INFO ROW //////////////-->
  <div class="row">
    <!-- BEGIN VOTES ARROWS -->
    <div class="col-lg-1">
        <%= render partial: 'votes/voting', locals: { post: @post } %>
    </div>
    <!-- END VOTES ARROWS -->

    <!-- BEGIN POST INFO -->
    <div class="col-md-8">
      <div class="col-md-8">
        <div class="row">
           <h2><%= @post.title %><br /></h2>
           <h4>Submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %></h4>
           <p><%= @post.body %></p>
         </div>
      </div>
    </div>
    <!-- END POST INFO -->

    <!-- BEGIN POST STATS -->
    <div class="col-md-3">
        <div class="row">
          <h3>
            <small>
              <strong><%= pluralize(@post.points, 'point') %></strong>
              <div>
                <%= pluralize(@post.up_votes, 'up vote') %>,
                <%= pluralize(@post.down_votes, 'down vote') %>
              </div>
            </small>
          </h3>
        </div>
        <div class="row">
          <% if current_user %>
           <%= render partial: 'favorites/fav_button', locals: { post: @post } %>
          <% end %>
        </div>
        <div class="row">
            <% if user_is_authorized_for_post?(@post) %>
                <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-info' %>
              <%# Here we override the method(:post) with :delete, so that the when the button is clicked the route called is delete %>
            <% end %>
            <% if current_user != nil && (current_user == @post.user || current_user.admin?) %>
                <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post? All comments will also be deleted.'} %>
            <% end %>
        </div>
      </div>
    </div>
    <!-- END POST STATS -->
  </div>
  <!-- END POST INFO ROW //////////////-->

  <hr />

  <!-- BEGIN COMMENTS FORM ////////////-->
    <div class="row center">
      <div>
        <% if current_user %>
          <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
      </div>
    </div>
  <!-- END COMMENTS FORM ///////////-->

  <hr />

  <!-- BEGIN COMMENTS SECTION /////////-->
      <div class="row">
        <div>
           <h3>Comments</h3>
           <%= render @post.comments %>
         </div>
      </div>
  <!-- END COMMENT SECTION //////////-->

</div>