config/routes.rb
Rails.application.routes.draw do
resources :advertisements

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#only:[] is used so /posrs/:id routes aren't created. Only posts/:post_is/comments
resources :posts, only: [] do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
end

resources :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]


post 'users/confirm' => 'users#confirm'

get 'users' =>'users#create'

get 'about' => 'welcome#about'

  get 'welcome/contact'

  #added my route to faq page
  get 'welcome/faq'

#default page the app will load
  root 'welcome#index'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  has_many :advertisements
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_create :send_favorite_emails

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  private
  
  def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_vote
  after_create :create_favorite

  default_scope {order('rank DESC')}
  scope :visible_to, -> (user) { user ? all : joins(topic).where('topics.public' => true) }
  scope :ordered_by_title, -> {order('title ASC')}
  scope :ordered_by_reverse_created_at, -> {order('title ASC')}
  #also tried:
  #scope :ordered_by_reverse_created_at, -> {order('created_at ASC')}


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
     votes.where(value: 1).count
   end

   def down_votes
     votes.where(value: -1).count
   end

   def points
     votes.sum(:value)
   end

   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

   private

   def create_vote
     user.votes.create(value: 1, post:self)
   end

   def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self).deliver_now
   end

end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
  belongs_to :topic, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :sponsored_posts
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
  validates :public, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
#registers an inline callback direcctly after the before_save callback
#{} is the code that will run when the callback executes
  before_save { self.email = email.downcase if email.present? }
  before_save :format_name
#||= shorthand for self.role = :member if self.role.nil?
  before_save { self.role ||= :member }

#this ensures that name is present
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
#first validation executes if password_digest is nil
#secord ensures that when updating a password it meets requirements.
  #allow_blank:true allows us to change other attributes with having to change password.
  validates :password, presence: true, length: { minimum: 6 }, if: -> { password_digest.nil? }
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

#Adds methods to set and authenticate against a BCrypt password. This requires you to
#to have a password_digest attribute.
  has_secure_password

  enum role: [:member, :admin, :moderator]

  def format_name
    if name
      names_array = []
      name.split.each do |names|
        names_array << names.capitalize
      end
      self.name = names_array.join(' ')
    end
  end

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
   current_user && (current_user == comment.user || current_user.admin?)
  end

  def no_comments(user)
    if user.comments.count == 0
      "#{user.name} has not submitted any comments yet."
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def no_favorites(user)
    if user.favorites.count == 0
      "#{user.name} has not favorited any posts yet."
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user !=nil && ((current_user == post.user || current_user.admin?) || (current_user == post.user || current_user.moderator?))
  end

  def no_posts(user)
    if user.posts.count == 0
      "#{user.name} has not submitted any posts yet."
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
     session[:user_id] = user.id
   end

   def destroy_session(user)
     session[:user_id] = nil
   end

   def current_user
     User.find_by(id: session[:user_id])
   end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
      current_user != nil && (current_user.admin? || current_user.moderator?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div>
        <ul class="nav nav-tabs collapse navbar-collapse" id="navbarSupportedContent">
          <li><%= link_to "Bloccit", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Topics", topics_path%></li>
          <div class="pull-right user-info">
            <% if current_user %>
                   <%= image_tag current_user.avatar_url(48), class: :gravatar %>
                    <div class="pull-right text-align-left gravatar">
                      <strong><%= link_to current_user.name, user_path(current_user) %></strong><br />
                      <%= link_to "Sign Out", session_path(current_user), method: :delete %></li>
                    </div>
               <% else %>
                 <li class="pull-right"><%= link_to " Sign In", new_session_path %></li>
                 <li class="pull-right"><%= link_to "Sign Up", new_user_path %></li>
            <% end %>
         </div>
       </ul>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>